### ISSUE TITLE
TypeError: 'NoneType' object is not callable in results = yolov2_box(opts, np.array(outs[0], dtype=np.float32)) 

### ISSUE THREAD

**Issue by samanthawyf** [taehoonlee/tensornets#18]
in get_v2_boxes,
results = yolov2_box(opts, np.array(outs[0], dtype=np.float32)) 
TypeError: 'NoneType' object is not callable

It seems that it failed to do this step: from .darkflow_utils.get_boxes import yolov2_box
How can I solve it?

**Comment by samanthawyf** [comment]
@taehoonlee 
Hi, I installed TensorNets 0.3.4 version by **pip install tensornets**. And the code is object detection example, in detail:
```
import tensorflow as tf
import tensornets as nets
inputs = tf.placeholder(tf.float32, [None, 416, 416, 3])
model = nets.YOLOv2(inputs, nets.Darknet19)
img = nets.utils.load_img('cat.png')
with tf.Session() as sess:
    sess.run(model.pretrained())
    preds = sess.run(model, {inputs: model.preprocess(img)})
    boxes = model.get_boxes(preds, img.shape[1:3])
```
and the error occurs in the last sentence, in detail
```
File "objectde_test.py", line 12, in <module>
    boxes = model.get_boxes(preds, img.shape[1:3])
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/detections.py", line 69, in get_boxes
    return yolo_boxes(opts('yolov2' + data_name(classes)), *args, **kwargs)
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/references/yolo_utils.py", line 95, in get_v2_boxes
    results = yolov2_box(opts, np.array(outs[0], dtype=np.float32))
TypeError: 'NoneType' object is not callable
```

**Comment by taehoonlee** [comment]
@samanthawyf, I suspect that part too. Can you shom me the exact message of `from tensornets.references.darkflow_utils import get_boxes`?

**Comment by samanthawyf** [comment]
@taehoonlee  I am sorry I don't know how to get the exact message. As I mentioned before, the error is:
_File "objectde_test.py", line 12, in <module>
    boxes = model.get_boxes(preds, img.shape[1:3])
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/detections.py", line 69, in get_boxes
    return yolo_boxes(opts('yolov2' + data_name(classes)), *args, **kwargs)
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/references/yolo_utils.py", line 95, in get_v2_boxes
    results = yolov2_box(opts, np.array(outs[0], dtype=np.float32))
TypeError: 'NoneType' object is not callable_
so the result of _from tensornets.references.darkflow_utils import get_boxes_ is  return _yolo_boxes(opts('yolov2' + data_name(classes)), *args, **kwargs)_.

Besides, I revised the code as:
_#try:
from .darkflow_utils.get_boxes import yolov3_box
from .darkflow_utils.get_boxes import yolov2_box
#except ImportError:
#    yolov3_box = None
#    yolov2_box = None_
and I get the error:
 _File "objectde_test.py", line 2, in <module>
    import tensornets as nets
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/__init__.py", line 51, in <module>
    from .references import YOLOv3COCO
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/references/__init__.py", line 3, in <module>
    from .yolos import YOLOv3COCO
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/references/yolos.py", line 37, in <module>
    from .yolo_utils import opts
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/tensornets/references/yolo_utils.py", line 8, in <module>
    from .darkflow_utils.get_boxes import yolov3_box
ImportError: cannot import name yolov3_box_

**Comment by taehoonlee** [comment]
@samanthawyf, It is easy. Please just run `from tensornets.references.darkflow_utils import get_boxes`.

**Comment by samanthawyf** [comment]
@taehoonlee 
```
>>> from tensornets.references.darkflow_utils import get_boxes
>>> 
```I ran it, and it passed.

**Comment by taehoonlee** [comment]
@samanthawyf, The Cythonization of `darkflow_utils` seem to have failed. Can you share the results of the following?
```
git clone https://github.com/taehoonlee/tensornets
cd tensornets/
python setup.py build_ext --inplace
```

**Comment by samanthawyf** [comment]
@taehoonlee I tried `python setup.py build_ext --inplace` as you mentioned, and retried my python file on tensorflow1.4, and it works.
However, on tensorflow1.2, the command didn't pass, the error is as follows:
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.dist import Distribution, Feature
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/setuptools/dist.py", line 21, in <module>
    from setuptools.extern import packaging
  File "/home/wyf/anaconda2/envs/tensorflow1.2/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by samanthawyf** [comment]
@taehoonlee  Thank you so much. I've solved the problem. On tensorflow1.2 platform,  first I updated `setuptools`, then I ran the command `python setup.py build_ext --inplace`, and it works finally. Thanks again for your help.
