### ISSUE TITLE
Model load issue

### ISSUE THREAD

**Issue by miha-skalic** [taehoonlee/tensornets#2]
Hello, 

I was trying to test your code and got stuck on loading models. See full log: 
```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensornets as nets
>>> import numpy as np
>>> 
>>> print(tf.__version__)
1.3.0
>>> print(np.__version__)
1.13.3
>>> 
>>> inputs = tf.placeholder(tf.float32, [None, 224, 224, 3])
>>> outputs = tf.placeholder(tf.float32, [None, 50])
>>> model = nets.Inception4(inputs, is_training=True, classes=50)
>>> 
>>> loss = tf.losses.softmax_cross_entropy(outputs, model)
>>> train = tf.train.AdamOptimizer(learning_rate=1e-5).minimize(loss)
>>> 
>>> with tf.Session() as sess:
...     nets.pretrained(model)
... 
2017-11-15 21:14:22.616901: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-15 21:14:22.616976: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-15 21:14:22.617005: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-15 21:14:22.767544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-15 21:14:22.767871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:01:00.0
Total memory: 10.91GiB
Free memory: 355.38MiB
2017-11-15 21:14:22.900139: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0xbea1700 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-11-15 21:14:22.900342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-15 21:14:22.900694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 1 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:02:00.0
Total memory: 10.91GiB
Free memory: 400.44MiB
2017-11-15 21:14:22.900850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 1 
2017-11-15 21:14:22.900869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y Y 
2017-11-15 21:14:22.900881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 1:   Y Y 
2017-11-15 21:14:22.900899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
2017-11-15 21:14:22.900914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
Traceback (most recent call last):
  File "/shared/miha/programs/miniconda3/lib/python3.5/site-packages/numpy/lib/format.py", line 640, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/shared/miha/py_homebrew/tensornets/pretrained.py", line 49, in pretrained
    __load_dict__[model_name](scope)
  File "/shared/miha/py_homebrew/tensornets/pretrained.py", line 101, in load_inception4
    return load_weights(scopes, weights_path)
  File "/shared/miha/py_homebrew/tensornets/utils.py", line 166, in load_weights
    values = data['values']
  File "/shared/miha/programs/miniconda3/lib/python3.5/site-packages/numpy/lib/npyio.py", line 233, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/shared/miha/programs/miniconda3/lib/python3.5/site-packages/numpy/lib/format.py", line 646, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'\xb1\xe0\xd7\xad\xdbf\x93\xae\xdcS\x90\xbe\x1d\x8f!?\x81\xdd^\xbf\x9a`\x9f=di\xae\xae \x07\x95.\xec\xcc\xc4\xbd\xa93\xaa\xae\x9d\xac\xef\xbd\xf1H<<\xa4,K?mz\xd8=RP\xcb.\xae\xad\xe1=ML\xa5.\x1e\x91\xff\xaeL\x11\xd4\xbe\xe2\xaa\xa0\xae\xd2\xeb\xa7\xbe\x84;\xb2>(\x1c\x02\xaf\x11\n\x00\xael\\\x88>\xea-Z\xbd@\'\x0f\xbdQ\x02\xb5\xae\x81n\xa5\xbe\xa5\xddU\xab"\xf8\x00/Z1\x92=v\xab\xb3.\x85\x06\xb2\xae|i\xf1\xbc\x93\xb5I?\x9c\x8b\x86\xbf\x873>=\xb9\xb9\x94\xaeQ!\x10\xaf\x00t>\xbe\xba\x80\x1c.\xa6F\x8e>\xa5\xb6\x01>\x15.S?\x01\xad]\xbe\x93\xe5\xe6.\xe3\xa2\xa2\xbe\xc2\xc7\x9c.,\xec\x10\xaf\xa5\x07\xd4=\x1e\x07\xba\xae\x8bW\x92>\x0e3h\xbe\xf3w\n\xaf\xd2s\'\xaf\x1e\xbf\x92\xbd\xa8\x82\xb8\xbd#\x12\xc6\xbc\xb9\xa2\xa1\xae\xad"t=\xae\x82G/\xb1L\xb3.\x19\xa8|\xbd<\x8f\xbb.\xaaE\x89\xae\xaco\x9c>i\x1b\x9c>\xde\x8c\x17\xbf\xa1k\x7f\xbd\xea\x13\xaa\xaet\x95^\xaf\xd0\x04\x04\xbex\xc2\x12\xafr\x08b\xbey\xe6\xb7\xbd\x1b\'\x17?\xe8\x823=p\x9e\x91.\x1byW>"\xf4\xe7\xae\xd8b\x8a\xad?]&>H\xf7\x94.\x7f\x0f\xa7>C+V\xbeP\x1f\xf2\xae+\xa1\xe3\xae\x0cC;\xbe\xa6\xe2\x95=\xac7C=\x05K\xb7\xae(\xcf\x90>\xf0(x\xae\xd0\xe3\xec\xad\xb7\xde\xe8\xbd|\x9cH\xae\xa2\x97\xae\xae\xb0e\xc9\xbe)\xb0\x9b\xbe\\\x16+>PG\xaa>\xe7\x87\xf4\xaej\x10\x98.(\\\x80>\'\x98\xab\xaeO\xcfl\xbe\x91\xf9\x87>\x03\xb68?\xe3q\xc6>\xf8P\xeb.\x92\xaa\x85>\x91\x82\x90\xaeNY\xd0\xac\x01\x8d\xcd>\xc0\x0c\xc5.\x0c<\xfb=\xaa\xa2\xe1\xbe\xb7B\x9f\xae\x95`\x8b\xae\xf5r\x13?\xc6*\n\xbf\x84\xb8M>\x8cg\x97\xae\xb6^\r\xbd\xbe\xaf\x1d\xad\xeen\xfd+\xdaT:>\xed\x17\xbc.\x1c>\xd1\xae$\x87\x9c;\'\xf6\xd6\xbe\xc5x\x05>W\x95\x14\xbe\x1a\x86\xa5\xae\x87"\x0f\xaf7Z\xfc>\xc7@\n.\x02\xcdr>\xb5\xf7o>\x1c\x13i?\xec8\x05\xbf\nM\xcc\xad\xebV\x05\xbf\x19\xfd\x0b\xae\x98\xd3\xbf\xab\x03\x04\x85=\xd9\x98\xa6\xae\x88\x8b\xe1\xbeB\x8a\xa4\xbe\xdb\xd0\xef\xae]\xa8A\xaf\x80\xad\x1e\xbeX;\x02\xbf\x0e$\x8f>^\x1a\xfd\xad\xdd\x7fm;7\x19F/\x1d\x19\xf7.v\xcd\xa2<\xbed\xe4.\xb0;\xcb\xae;}\xe1>L,P\xbeL{\xa7=\xf4\x83\xab\xbei\xe0\xc9\xae\xb4\xb5V\xaf\xde]\x89>^\x16\x15\xaf \xac\xcf\xbed\xa7\xff\xbe\x08N)?\xfd^\xfd=n\xc3\xa7.\x06\xf7\x07>\x9c\xccs\xaeU=\xc0+\xb8\x027\xbexv\xa3.\xd63J\xbe\xf0\x96\xbe;*\xc5\xe8\xae\x02X\xed\xae|E\xb4\xbek\xfa\x89\xbe\x8c\\\x98>\xc5\x97\xac\xae\x7f\\\'<\xc9Dp\xae\x0e\xa0\xbf\xad\x8f\x99\x9a\xbcF(\x12.?\x0c\x07\xaf\x0b\x17\xa2\xbeR4-\xbeJ\x99\x1d?\xb6\xa2D>\xc3K\xee\xae\xcf\x0f\xca.z%+>kz\x91\xaeX\x01\xb9\xbd\n\xd3\x80>#\xd6\xf0>\xcd8\x82>\x94k\x14/\x90\xd7\x12>\xd6\x01v\xaeQU\x04\xaf\x9e\xaa\x04?\x91\xf6\x98\xae\x1f#\r?\\\x98\x1b\xbf\x95\x8c\xa3\xad\x10`\xa6.\xed\x9e\xda>fr\x81\xbf\xa1\xeb\x1b?\x99(\x88\xae\x884\x0f\xbe(\xbc]\xadP\xe7\xf2.~\x12\xce=\xa4\xde\xb6.\x1b\x0e\xdd\xae*\xaf\x83\xbaX\xe6\xb5\xbe\x8cjH?\xcfs\x0e\xbe\x0c\x1a\xbd\xae2a\x90\xad\x8a\xbb\xc0>\xc9\x82-.\xebj:>\x85\xda\x94=\xeca&?\xd4\xa2\x81\xbe\xc4\xaa\xfa\xac\xf0o\xa8\xbe\x8e\x85\x0e\xaeL{\x87\xacR\xeb\xca\xbeA\n\x9f\xaeY[\xe2\xbe\xbek\\\xbe\x0e\xb7\xc2\xaeS\x13\t\xaf\xc0\xbc\xd5\xbd\x9a\xdeh\xbf$\x1e+?e\x00e\xaeQ\x1d=<\xb6\xf9)/c*\xb1.\xe7Io\xbd~\x94\xc2.!\xe3[.(\x98\x91>\'\x93\xe7\xbc\xd5\xa1\xad>\x82H$\xbe1k\xbc\xae%+\xfd\xad\xbe\x14\x8b>\xc0\x1a\x18\xaf\xee;<\xbe\xf4X\x82\xbe\x1e\\\xce>\x955 \xbcH\x17\xb3.\x9c\x0f\x8b==*j\xae\x02`x\xab\xbc\xdd\xe9\xbeuS\x92\xae\xe5J\xda\xbeP\x1f\xd6=\xb2\xb0\xdf\xae\xa6 \xf8\xae\x11\x85l\xbe\x9e\x8d%\xbf\xda\xdc\x1b?^\xe4\x94\xaeg\xc7\x04>\xe2w\x8e\xae_Y\r/\xe8\xe1\xc0\xbd?\xa8\xbf.\xde\x05\x88\xaek`\xc6\xbe\xaekB?\x93\xcb\\\xbf\xbc|\xce>T\xf2$.\xcc\x12y-\x96\xa4\xce\xbdn"\xb5\xae\x01\x15\x00\xbe\xb7\xf1Z>\xeeW=>\x01\xae\xa5>L\xa2\xc5.gW\x8e>\xa8\xc3\x05/\xc3\x0c\x8d-b0<\xbe\xce\xab\xb8\xae\xa2\xff\x0b\xbfR^\x02=\xaa\xe4\xe8\xaep\xaa\xfe.Y\xa8\x13?Y\xa7I>\x00t\x00\xbf?\xcd\xac\xae\xe0\xff\xad>\xe7\xf4\xee.\xbcZ\xec.+\xee\x10>\xe2\xe2\x9e.\xfd\xfa\x8f\xaew|\x0c\xbdy\xb3e?\xad\xb5\x82\xbf\xb4\xd7\xce\xbd\xa91\xaf\xae\x94t\xea\xae4\xc6:\xbem\xc3\x99-J*\x8f>\xf1\xaft>\x96f\x12>ZE\x02\xbf\xf5\xad\xb6.\x9a1\xe5\xbe\xe7\x1c\xe5.\x89\x11\xfd\xadt\xc2\x82>\x94\xcd\xb4\xae\xfbCq\xbdDd\x17\xbe\t\xaa\xdf\xaea\x9f\x04\xafx\xedH\xbe-\x9e;>D~\xd9\xbe\xea(\xaf\xae\xc7bK\xbed6\x16/N\xd8\xaa.S\x98"\xbdd\xc9\xa8.\xba8\xf0.I\x9b\xdd>S\xe2\xb7>\x90\xf4\xfe\xbe\x15\xc1\xd4\xbe\x87\x98\xbd\xae\'\x11@\xafv\xd3:\xbe\xbc \x10\xaf \xd6\xbd\xbe/>\xee\xbe\xd5\xa3\t>\x05\xcd.>6\x95\x8d.Pd\xd2=\x01\x0e\x9e.\x93\r\xf4-\xb3\x02a>\xdc\x0c\xad\xae:\xd5\x01>\xae]\x12\xbeV}\xf8\xae}\x99\xe9\xae\x1c\xb4\xca\xbeY\xb7\x80>\x02\x8bp\xbe%\x15\xb4\xae\xc7yO\xbe\xac\xfe\x83\xad\xc9\xdbl\xad_\xe4\xb7\xbc\xcd\xab\x8b.\x1d\x99\xd3\xae|\x0e\x07\xbf(\xe2\x8b\xbe=\xb1\xe1<\x9bi"?q\xb2l.\xf8\xa8\x1a\xad\xbfo\x8f\xbdx=\xb0\xae\xee^2\xbeR\xe4\x06?\x0b`)=\xb4\xc62?\xe9\xc8\xcd.\x01\xf7\xbe>\x84-\xed.Z\x01\xe2\xae\x10\x96E?\xb5Q\x99\xaeXl\xfd\xbd\xba\x1b\xa8>\xdex\x9a\xae1\x86\xad.\'fR?\xff!H\xbe\x86\x05\x94\xbe\x15\x9b\xb3\xaeB\xd2B?\xe0\xfe\x8f+Fz\xe0,_T\x98>\x03\x88\x95.\xe9\xf8\xc3\xae}\x0cI\xbd\xb0M\xd1\xbe\xabXX\xbb\x03\xd0o\xbe#I\xa2\xae-\x94\x0f\xaf\xff\xdaZ=\xa8\x06\x98\xad\x14@\xaf>\xf1\x94\x14?\x05\xc1\x8c=\x9fyE\xbfA\xff\xc7.\xcc\x84H\xbf\x9fs\xfe.q\xec\x01\xaf\xf8I\'?\x11_\xa9\xae\x0cH\xd6\xbe@FV?h\xf9\xc5\xae\x85\x19\x0f\xaf>\x8e\x93\xbe\x82{.\xbe\x9f\xe2\x94\xbe\x07\x14\x7f.\x8c\xc2\x9d\xbeO\x1cC/a\xb6\x1f\xad\x04\xf5\x97=|\xad\x94.\x8f4\x93\xae\xa4s\x0c?\xb0\xa8(\xbe\x8c\xd9D<\x95\xa0\x1b\xbf\x1b\xe0\xbb\xae\xf6\xc7R\xaf\xea\x0bd=N\x88\x16\xaf+\xff\xff\xbe^\x93^\xbf\xb2&\xb3=\xc3\x8b\xc4>\x9a\xf7\xa9.\x1ev\x00=U5\x88\xae\xd3"c*\x12I,>?\xdao\xae\xcd\x02G\xbe\xdb\x10\x08?\x12\x1b\xcc\xae>{\xea\xae2\xd7\x10\xbfg\xb0t\xbbn\x8b\xdb\xbd\xcd\xe9\xd3\xae\xbfZ\x07\xbft?Y\xae\xc9*\x1a\xadR\x80\x15>\xcd\xa4\xcb.u \x06\xaf\x17\xf0\xbb\xbe\xfd\x95\xe8\xbe\xd6\xe5D?\xa0\xbd\x96>\x9a\x15:.\x11b\xe0.\xc0\xa52\xbf\x17a\xbe\xaeX\xfb\xe4\xbd u\xbc>H%z\xbd\x8fO\xc7>x\x8a\xec.2\nv>e\x89\xdb.\xaa\xe2\xfc\xae\x87\x83\x9d>,\xd6\x97\xae$q\x0f?\xba\x82\xdf\xbdK\xbd\x81.\x8e\n\x9d.$\t\x0b?\xfd\xfa\x0e\xbfz\xba(>\xbd\x01\xa7\xae\xffl*\xbb\xc5y\',\'_\x0b/$\xa4G>\xb0\xf0\xb4.Nw\xc9\xaeE`L\xbd\x93\x8c+\xbf\xa9g|?w\xc6\x04\xbe\xbe$\xad\xaeN\x8a!\xaf\x81\xb6G\xbfX\xc9G\xadQel>\xe7\xce\x96>e\xf0Q\xbc\x03\xd5\xf9\xbe`\xc0\xf0.\x05\xfb\xf0\xbe\xc7`\xf9.\xa3\xe6\x96\xab4\x90\xcf\xbe\xf5\x81\x97\xae\xfe\xe2\xa6\xbd\x7f\x16\xa8>.\xba\x00\xaf\x04\xe1\xdd\xad?\x02\x1f\xbeC\xbd\xfc\xbe\xd4\x03\x05>\x13\x98\x97\xae=\xff\x15\xbd\xed\x159/\xc9\xda\xe7.\xca\xcan\xbcMy\xa0.\x9a\x12\x8d.\xb7\xa7\xc6>\xd2U4\xbe\x86\xae\x05?3\xc3\x93\xbe\xd2Y\xbd\xae&\x8c*\xaf\xb0H\x97\xbe\x0f\x19%\xaf\xa9\xca\x90\xbe\xa3\xf2\x06\xbf\xd6g\x9b\xbc!)U>,v\xab.\x81\xf8\xa4=\xcd\xc1\xb0\xae]\x8b\xf8*\x89d\xc9\xbe\x10\xc0\x91.|`\\\xbe(\xfe\x86><\n\xf6\xae\xef\xfb\x02\xafL\xfc\xad\xbe1U\x9d\xbe!\xe6B>\xa7\x1f\xb3\xaeX\x0cq\xba;\xfe\x87\xae\x9c7\xcf-[\x7f\x08=~\xb1\x03/\xdc:\xc4.T\xfa\x9a\xbe\xfdJ\x89\xbd+m%\xbe\xbf\x1e\xa9>\x1b\xa9W.e\xd1\x9f.\xf2\xeej>qz\x90.\x0c\xaa\xc6<\xc3\xe8\x18>\xfb\xe38\xbf,\xd0@>\xd0\x01\xbd.W\xff6>\x07\xca\x03/&\xee3.+\x00\x06\xbf\x07\xe6\xac\xae\xb5:\xe1\xbd\x1fM\x83=\x07\x82\xf9\xae$\xf3\xa2.\xd9\xa5\xfb>\xf6\x13\x16?\x17.i\xbfU2\xac\xae\xc7\\\xce=\xea\xfe\x10/\x0e\x85\xd2.`\xf3\x0b>e\x0b\xc6.:sz.y\xb7\xfa\xbb\x18\x80I>\x062\x8d\xbe\xe7,\xda\xbd\x1b\xc9\xa2\xae\xa4\xec\x0b\xaf\x9d\xef\x14>$\x02%.x\xd2)>u\x07\x92=\xb4\xb5`\xbf8\xf1@\xbe2\x1e\x93.\xcf\xbd~\xbe!\xc4\xf8.\xa7\x07.-\xbboJ\xbe\xa6\xd4\xcf\xae\xfe=v>\x8e\x940\xbe\x0c\xb7\xda\xaeC\xc0\xde\xad?4\x0b\xbe>%\x11?\x90\xdaJ\xbf\xad{\xba\xae\xd6\x03\xf6\xbdfx\x0e/a~\xbe.\xd5:\x94\xbd\x06\xb5\xbb.\x8f"\xb5.\x0b\x7f\xbe>(\x86\xc0\xbd\xdc\x17\x9b\xb8\x01\r\xa8\xbe\xc6\x08\xb0\xae(GB\xaf\xef\x17\x90\xbdb\x02\x8f\xaeV,@\xbe\x9aY7\xbeX\x94\x16\xbf\x89\xf1\xfe\xbb\xb3\xc7\x89.\xb74p=\xd7\x92\xe4.\xa3\x15F.\xcb\xee\xfd=\xccu\x10. \x99\x14>8\xaab\xbeo\x95\xd6\xaeD\xc8\xfb\xaeZ]\xb7\xbeK\xf0\x11?\xfa\x12\x08\xbf|\xb4\xc7\xae\r\x04\x10\xbb.\x1ch.\x8a\xaax\xad)\xa3\xf9\xbc\xbfO&\xae\xec\xedE.\x80\x89\xc6\xbe\x93\xbc\xa7\xbd\x1d\xd1\xae\xbd\x85w\xd0>/oL.q`\x9a.\x98R\t?k\xbd\x90.\xae\xd3\xa6\xbdk\xa1\x8e>\xe5\xadM\xbf\x02\xa6\xbf>s\x0e\xd1.f\x8a\x85>W`\x00/\xd1T\xef\xae$u\xc3\xbe\x8b\xfe\x91\xae\x17\xb4\x10>\x91\xf9\xbb>\xea\r\xe8\xae~\xa2\xad.3,\x13?R\x85.>\xf0\x9b\x14\xbf\xcbr\xd2\xae8\xc6\x01?\x04\xfd\xea.\xa7L\x10/\xefH\x84>;\xa8\x9c.\xbe\x9f\r\xae\xd0\x94]\xbd\xd2\xbc\xd4<\np\x08\xbe\xa9\xf8\xa0\xbd\xca\xc7\x8b\xac\xb1\x1b"\xafn\x15\x1c?q\xd6\n.N\xa1f>3\x94\x9b>0\x1f~\xbf\xeb\t\xf1\xbe\x05)\xb7.\x100\xf4\xbeJf\xe5.\x06\x1b\xc2\xad\x85M\x8e\xbd=]\xa7\xae\xd1\xe0,?\xf2@\xb0>\xdd-\xca\xae\xdbC\xd4\xad\xcc%\x15\xbe\xb4Y@>#z\x19\xbf:\x83\xb2-\te\x82\xbe{\t\x1b/\xa1\x0e\xe2-\xb2\x10\xa4<\xf7\x9f\xa3.\xed%t.\xdby\xd9>\xdf\xf0I\xbd~\xdd\xbe\xbdm(\xab\xbe,\xb1n.\x03\xcc+\xaf\xb6\xb8x>\x87\x96\x11\xae\\I\x8a\xbe\x94\xf8\xd6\xbe\x18M+\xbfj\x01/>\x86\xd2\x8d.\x82Ao=@Q\xbb.\xcc\x95\x17-\x0f\x82\xd8=\xc0\'$\xae\xee\xc5\xa8>\x91\n\xa6=xq\xbb\xaeC\x15\xe3\xae\xd4\xba\xcb\xbe\xd6\xa5g>\x17\x18\xa9\xbe\x985\xfb\xae\xb6\xcc\x9b\xbe\xdf\xd2\x94\xae`\xad\xb9,\xc3_\xca=\n\x91\xc7\xad\x08\r\x99\xae\xe9\xccn\xbe\xa3f&\xbd6\x81\xd5>\xc7\xbe)<)Sd.\xf4X\xa9\xad\xd1$\x81\xbe!\xcd{.\xe5eg\xbcc\xaf\x18=\x04\x19)\xbfe6d=\xcd\x14\xe9.T\xae\xf7=\x82m\xfc.KG\xeb\xae{8\xd7\xbe\xa6\xa2q\xaeT\x88}\xbe\xd6\xb71\xbd\x80j\xe2\xae\xbaQ\xa4.\x87\xd2?>a\xa5\x0f\xbd!Y\xc4\xbdL#\xc9\xae\xbf\xb6\x81\xbeh|\x0c/\xf4\xb8\xaa.\x07u\'>\xb4_\xdc.\x89K\xc2\xae"\r]\xbdE\xa3\xa7\xbd\xf76\x0c?\x01\x92r=\xae\xb69\xae\xd9\x7f\x0e\xaf5\x17\xff\xbe\x01\x18\xc1-m\x84A>\x95&S=~lD\xbfa\xc6\x8b\xbe\xfd^\xef.`\xcbA\xbe\xd3p\n/5\x04\x0e\xaf\xe5\x97\xcc\xbc(U\xa0\xae\xc8>m>\x07\xb8\xce\xbe/\x15\xd4\xaeP\xcc\x16\xaev\xcf\x95\xbdR\x84\x87\xbcrC\x1c\xbe\xd8\xa06.\x11\xd56\xbb4\x0f\x1d/\x92\x10\xa1.<\xdc]\xbd\xda\xdb\xd4.:\xa7|.\x1c\xb2\x90>\xcd\x1bC<\x840\x7f>q\xe6\x83<\x93\xfdL.%\x10N\xaf\xf5\xeb#\xbe\xa1\xbe\x1a\xae\xca\x0c\x97\xbd\xcdPf\xbeq\xae\x16\xbf\xa0\xd6\x1d=\xa3\x8e\xa1.\x1b\xfdi>\x82L\xbc\xae?\xbb#\xae\xd6c]>\x8e4\xa1\xac\t\xf9\x88=s"\xbe\xbe\x92s\xd3\xaen%\xf3\xaew\x9fe\xbe+\xb6\xa2=\xf1OI\xbc\x1en\x00\xaf\x13\x05\x85>\x8a%\x83.\xff\x99\xdb\xac\x98S\xcc\xbb', 0, 1, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load
```

I'm using the latest version of tensornets. Any clue why this is happening?

**Comment by taehoonlee** [comment]
The problem is solved by adding the encoding argument (see [updates](https://github.com/taehoonlee/tensornets/commit/6c4244852e6f571dcd7d7959da8c3288a8f46932)). The pickle files generated on Python 2 seem to be encoded as `bytes`. Thank you for reporting the issue, @miha-skalic!
