### ISSUE TITLE
Error when running pip install tensornets

### ISSUE THREAD

**Issue by jafetmorales** [taehoonlee/tensornets#24]
This is the output when running <code>pip install tensornets</code>
```
Collecting tensornets
  Downloading https://files.pythonhosted.org/packages/b9/b7/dd956d687d5a45ccac1275dba1f522f6dedeaab43e5e540c2627fa4d6f9c/tensornets-0.3.4.tar.gz (576kB)
Building wheels for collected packages: tensornets
  Running setup.py bdist_wheel for tensornets: started
  Running setup.py bdist_wheel for tensornets: finished with status 'error'
  Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-emz1qnku\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\jmorales\AppData\Local\Temp\pip-wheel-7vgpy5t9 --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\tensornets
  copying tensornets\capsulenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\darknets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\densenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\detections.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\inceptions.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\layers.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\middles.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\mobilenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\nasnets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\ops.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\preprocess.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\pretrained.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\resnets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\squeezenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\utils.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\vggs.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\zf.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\__init__.py -> build\lib.win-amd64-3.5\tensornets
  creating build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.5\tensornets\datasets
  creating build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\yolos.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\__init__.py -> build\lib.win-amd64-3.5\tensornets\references
  creating build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  running egg_info
  writing tensornets.egg-info\PKG-INFO
  writing top-level names to tensornets.egg-info\top_level.txt
  writing dependency_links to tensornets.egg-info\dependency_links.txt
  reading manifest file 'tensornets.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'tensornets.egg-info\SOURCES.txt'
  copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\references\coco.names -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\voc.names -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\darkflow_utils\__init__.pyc -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.pyc -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.so -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.so -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  running build_ext
  building 'tensornets.references.darkflow_utils.nms' extension
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  creating build\temp.win-amd64-3.5\Release\tensornets
  creating build\temp.win-amd64-3.5\Release\tensornets\references
  creating build\temp.win-amd64-3.5\Release\tensornets\references\darkflow_utils
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -Ic:\users\jmorales\appdata\local\programs\python\python35\include -Ic:\users\jmorales\appdata\local\programs\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tctensornets/references/darkflow_utils/nms.c /Fobuild\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils/nms.obj
  nms.c
  c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  tensornets/references/darkflow_utils/nms.c(2380): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  tensornets/references/darkflow_utils/nms.c(2389): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  tensornets/references/darkflow_utils/nms.c(2439): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  tensornets/references/darkflow_utils/nms.c(22288): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
  tensornets/references/darkflow_utils/nms.c(22294): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\jmorales\appdata\local\programs\python\python35\libs /LIBPATH:c:\users\jmorales\appdata\local\programs\python\python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" m.lib /EXPORT:PyInit_nms build\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils/nms.obj /OUT:build\lib.win-amd64-3.5\tensornets\references\darkflow_utils\nms.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils\nms.cp35-win_amd64.lib
  LINK : fatal error LNK1181: cannot open input file 'm.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

  ----------------------------------------
  Failed building wheel for tensornets
  Running setup.py clean for tensornets
Failed to build tensornets
Installing collected packages: tensornets
  Running setup.py install for tensornets: started
    Running setup.py install for tensornets: finished with status 'error'
    Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-emz1qnku\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-gqdxhlji\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\tensornets
    copying tensornets\capsulenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\darknets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\densenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\detections.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\inceptions.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\layers.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\middles.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\mobilenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\nasnets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\ops.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\preprocess.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\pretrained.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\resnets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\squeezenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\utils.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\vggs.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\zf.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\__init__.py -> build\lib.win-amd64-3.5\tensornets
    creating build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.5\tensornets\datasets
    creating build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\yolos.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\__init__.py -> build\lib.win-amd64-3.5\tensornets\references
    creating build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    running egg_info
    writing tensornets.egg-info\PKG-INFO
    writing top-level names to tensornets.egg-info\top_level.txt
    writing dependency_links to tensornets.egg-info\dependency_links.txt
    reading manifest file 'tensornets.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'tensornets.egg-info\SOURCES.txt'
    copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\references\coco.names -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\voc.names -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\darkflow_utils\__init__.pyc -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\box.pyc -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\get_boxes.so -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.so -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    running build_ext
    building 'tensornets.references.darkflow_utils.nms' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\tensornets
    creating build\temp.win-amd64-3.5\Release\tensornets\references
    creating build\temp.win-amd64-3.5\Release\tensornets\references\darkflow_utils
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -Ic:\users\jmorales\appdata\local\programs\python\python35\include -Ic:\users\jmorales\appdata\local\programs\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tctensornets/references/darkflow_utils/nms.c /Fobuild\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils/nms.obj
    nms.c
    c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    tensornets/references/darkflow_utils/nms.c(2380): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    tensornets/references/darkflow_utils/nms.c(2389): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    tensornets/references/darkflow_utils/nms.c(2439): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    tensornets/references/darkflow_utils/nms.c(22288): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
    tensornets/references/darkflow_utils/nms.c(22294): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\jmorales\appdata\local\programs\python\python35\libs /LIBPATH:c:\users\jmorales\appdata\local\programs\python\python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" m.lib /EXPORT:PyInit_nms build\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils/nms.obj /OUT:build\lib.win-amd64-3.5\tensornets\references\darkflow_utils\nms.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\tensornets/references/darkflow_utils\nms.cp35-win_amd64.lib
    LINK : fatal error LNK1181: cannot open input file 'm.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

    ----------------------------------------
Command "c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-emz1qnku\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-gqdxhlji\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-emz1qnku\tensornets\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by taehoonlee** [comment]
Thank you for trying TensorNets, @jafetmorales. It is hard for me to support Windows. I am so sorry. How about trying Conda or Docker?

**Comment by nidhitvaishnav** [comment]
HI, I am using
_Python : 3.6.5
OS: Windows 10_
And I am trying to install TensorNets in Anaconda Navigator, but Tensornets is not available in the environments. And when I tried to install from anaconda command prompt in conda then I got the same error.
So can you please make it supportable to at least anaconda navigator?

**Comment by taehoonlee** [comment]
@nidhitvaishnav, Can you try `pip install tensornets` rather than `conda install`?

**Comment by jafetmorales** [comment]
@taehoonlee I was strictly testing whether the `pip install tensornets` from the `README` worked. Maybe we can mention it might not be supported on Windows.

**Comment by taehoonlee** [comment]
@luitcifer, is your problem related to TensorNets? What are your exact command and the error message?

**Comment by siaqadri** [comment]
i download this package please tell me the procedure how can i install it from command prompt.

**Comment by taehoonlee** [comment]
@siaqadri, please try `pip install tensornets`.

**Comment by prayagverma01** [comment]
C:\Users\HP\AppData\Local\Programs\Python\Python38\Scripts>pip install tensornets
Collecting tensornets
  Using cached tensornets-0.4.6.tar.gz (651 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for tensornets from https://files.pythonhosted.org/packages/71/22/2c9402bbf142b94dc39d8a3c9884690ae87706a8bc1453d6cf0630525173/tensornets-0.4.6.tar.gz#sha256=e1095082b45a06168d56450d8c8fa49780d8aef8d4d1fcc64efceadb743f9ceb.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\hp\appdata\local\programs\python\python38\python.exe' 'c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmp4lk9tcoj'
       cwd: C:\Users\HP\AppData\Local\Temp\pip-install-htstuod0\tensornets_e09ef89525b34cfba62886ca246ff767
  Complete output (22 lines):
  Traceback (most recent call last):
    File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 1, in <module>
      import numpy
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "C:\Users\HP\AppData\Local\Temp\pip-build-env-2siywsqn\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('C:\\Users\\HP\\AppData\\Local\\Temp\\pip-build-env-2siywsqn\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hp\appdata\local\programs\python\python38\python.exe' 'c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmp4lk9tcoj' Check the logs for full command output.






how to fix this error
