### ISSUE TITLE
Unable to pip instal tensornets on production

### ISSUE THREAD

**Issue by benmezger** [taehoonlee/tensornets#50]
For some reason, `tensornets` fails to install when doing `pip install -r requirements.txt` on production.

```
Step #1 - "builder": ModuleNotFoundError: No module named 'numpy'
Step #1 - "builder": import numpy
Step #1 - "builder": File "/env/src/tensornets/setup.py", line 1, in <module>
Step #1 - "builder": File "<string>", line 1, in <module>
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder": Complete output from command python setup.py egg_info:
Step #1 - "builder": Cloning https://github.com/taehoonlee/tensornets.git to /env/src/tensornets
Step #1 - "builder": Obtaining tensornets from git+https://github.com/taehoonlee/tensornets.git#egg=tensornets (from -r requirements.txt (line 12))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/tensorflow-1.15.0rc2-cp37-cp37m-manylinux2010_x86_64.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/0a/a9/a5ffe715d3475fed0a79be8e13ef638abbd1c013fdbe8f43892f06336b82/tensorflow-1.15.0rc2-cp37-cp37m-manylinux2010_x86_64.whl (412.3MB)
Step #1 - "builder": Collecting tensorflow==1.15.0rc2 (from -r requirements.txt (line 11))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/Pillow-6.2.0-cp37-cp37m-manylinux1_x86_64.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/34/b7/fb24ad352b747340ec1975c84c30cca37bb93a0079e037d1f0930afd65ad/Pillow-6.2.0-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
Step #1 - "builder": Collecting Pillow==6.2.0 (from -r requirements.txt (line 10))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/numpy-1.17.3-cp37-cp37m-manylinux1_x86_64.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/00/4a/e34fce8f18c0e052c2b49f1b3713469d855f7662d58ae2b82a88341e865b/numpy-1.17.3-cp37-cp37m-manylinux1_x86_64.whl (20.0MB)
Step #1 - "builder": Collecting numpy==1.17.3 (from -r requirements.txt (line 9))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/Cython-0.29.13-cp37-cp37m-manylinux1_x86_64.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/f1/d3/03a01bcf424eb86d3e9d818e2082ced2d512001af89183fca6f550c32bc2/Cython-0.29.13-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
Step #1 - "builder": Collecting Cython==0.29.13 (from -r requirements.txt (line 8))
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz (377kB)
Step #1 - "builder": Collecting psycopg2==2.8.3 (from -r requirements.txt (line 5))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/django_extensions-2.2.3-py2.py3-none-any.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/43/42/d2aa7c39739b81b949aa0c2e8aab62f8b0b1ea034aac862b54ef7063b49c/django_extensions-2.2.3-py2.py3-none-any.whl (223kB)
Step #1 - "builder": Collecting django-extensions==2.2.3 (from -r requirements.txt (line 4))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/django_environ-0.4.5-py2.py3-none-any.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/9f/32/76295a1a5d00bf556c495216581c6997e7fa5f533b2229e0a9d6cbaa95ae/django_environ-0.4.5-py2.py3-none-any.whl
Step #1 - "builder": Collecting django-environ==0.4.5 (from -r requirements.txt (line 3))
Step #1 - "builder": Saved /tmp/tmpkyWvcV/wheel/Django-2.2.6-py3-none-any.whl
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/b2/79/df0ffea7bf1e02c073c2633702c90f4384645c40a1dd09a308e02ef0c817/Django-2.2.6-py3-none-any.whl (7.5MB)
Step #1 - "builder": Collecting Django==2.2.6 (from -r requirements.txt (line 2))
Step #1 - "builder": INFO `pip_download_wheels` stdout:
Step #1 - "builder": INFO pip_download_wheels /env/bin/python3.7 -m pip wheel -w /tmp/tmpkyWvcV/wheel -r requirements.txt --disable-pip-version-check
Step #1 - "builder": INFO starting: pip_download_wheels
Step #1 - "builder": INFO pip_install_wheel took 0 seconds
Step #1 - "builder":
Step #1 - "builder": You should consider upgrading via the 'pip install --upgrade pip' command.
Step #1 - "builder": You are using pip version 19.0.3, however version 19.3.1 is available.
Step #1 - "builder": INFO `pip_install_wheel` had stderr output:
Step #1 - "builder":
Step #1 - "builder": Successfully installed wheel-0.33.6
Step #1 - "builder": Installing collected packages: wheel
Step #1 - "builder": Downloading https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Step #1 - "builder": Collecting wheel
Step #1 - "builder": INFO `pip_install_wheel` stdout:
Step #1 - "builder": INFO pip_install_wheel pip install wheel
Step #1 - "builder": INFO starting: pip_install_wheel
Step #1 - "builder":
```

For some reason, tensorflow is not able to find numpy. I have tried installing using the distribution package before installing tensorflow, but the same happened. Any idea?

**Comment by Zain-Gill123** [comment]
Hey! Did you find any solution to this?
